### ISSUE TITLE
Missing ..\Link\MadLogger.cs

### ISSUE THREAD

**Issue by casualbit** [mad2342/MightyChargingJuggernaut#1]
I'm running into an issue rebuilding the mod. After cloning, and opening the solution in Visual Studio 2019, I'm missing the 'MadLogger.cs' file, as indicated by the error:

Error	CS2001	Source file '<root>\MightyChargingJuggernaut\Source\MightyChargingJuggernaut\..\..\..\Link\MadLogger.cs' could not be found.

Was this not commited to the repo? Thanks!

**Comment by mad2342** [comment]
Please see https://github.com/mad2342/MadLogger
